stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - docker build -t server .

test-job:
  stage: test
  image: golang:1.25.4-alpine3.22 
  script:
    go test ./...

deploy-job:
  stage: deploy
  script:
    - docker-compose up -d