stages:
  - build
  - test

image: golang:1.25.4-alpine3.22

build-job:
  stage: build
  script:
    - echo "building golang_app"
    - go build -o myapp

test-job:
  stage: test
  script: 
    docker-compose up --build
    go test ./...
    docker-compose down
